<h1><center> PPOL 5203 Data Science I: Foundations <br><br> 
<font color='grey'>Problem Sets II<br><br>
Tiago Ventura</center></center> <h1> 


# Introduction to Problem Set 02

This problem set will focus on: 


- Writing functions    
- List comprehension
- Generators
- Numpy
- Creating Pandas DataFrames


# 1. Writing functions (20 pts)


Using the following data, write a function called  mutate() that takes the nested list data and a new list as input and returns a new nested list combining the input list to the nested list. Notice, your single function must support concatenating the nested list with the input list by row or by column.  

Important points:

- You should use an argument called axis to indicate the row-wise or column-wise option.

- Make sure the function can only deal with inputs of the same size for the column-wise operation 

- Make sure you include a docstring with your function

In [49]:
# input data
data = [
  ["Var1","Var2","Var3"],
  [1,"Apples",True],
  [4,"Horses",None],
  [-1,"Small Birds",False],
]

In [73]:
## add your response here
def mutate(data, new_list, axis):
    """
    Concatenate a new list to a nested list.

    Imputs:
    data(list): The nested list.
    new_list (list): The list to concatenate to the data.
    axis (int): axis = 1 for row-wise operation, axis = 0 for column-wise operatioin.

    Returns:
    list: The nested list combine with the new list.

    Raises:
    ValueError: If the input lists size are not the same (column-wise operation).

    Example:
    data = [[1, 2], [1, 2]]
    new_list = [1, 1]
    mutated_data = mutate(data, new_list, axis=1)
    print(mutated_data)
    """
    
    # for row-wise operation
    if axis == 1:
        # combine data with new list
        return data + new_list
    # for column-wise operation
    elif axis == 0:
        # check if two list are the same size
        if len(new_list) != len(data):
            # if not same size, return an error message
            raise ValueError("Unable to do column-wise operation if lists are not the same size.")
        # if same size, combine data with new list
        return [data[i] + new_list[i] for i in range(len(data))]
    # if input does not indicate row-wise or column-wise operation, return a error message
    else:
        raise ValueError("Use axis = 1 for row-wise operation, axis = 0 for column-wise operatioin")


In [74]:
mutate(data, data, axis = 1)

[['Var1', 'Var2', 'Var3'],
 [1, 'Apples', True],
 [4, 'Horses', None],
 [-1, 'Small Birds', False],
 ['Var1', 'Var2', 'Var3'],
 [1, 'Apples', True],
 [4, 'Horses', None],
 [-1, 'Small Birds', False]]

# 2. Practice with numpy arrays (20pts)

## 2.1 Converting a list to an array

We provide you with a list names roles_list_of_lists

- A. Transform the roles_list_of_lists into a 2D numpy array; call it roles_array
- B. Print the dimensions of `roles_array`

In [2]:
## setup
import numpy as np

## input
roles_list_of_lists = [["Tiago", "Ventura", "Professor"], 
                      ["Sierra", "Sikorski", "Teaching Assistant"]]

In [6]:
## add your response here

# transform to array
roles_array = np.array(roles_list_of_lists)

# print dimension
roles_array.shape

(2, 3)

## 2.2 Subsetting arrays using True/False (boolean) indicators

- A. Create a boolean indicator for rows where the role (third column) == 'Teaching Assistant' and print that indicator
- B. Use that boolean indicator to subset roles_array store the array as roles_TA 
- C. Print the `roles_TA` array and its dimensions (should be 1x3)

In [7]:
## add your response here

# Create a boolean indicator
role_indicator = roles_array[:, 2] == 'Teaching Assistant'

# Use boolean indicator to subset roles_array
roles_TA = roles_array[role_indicator]

# Print the roles_TA array and its dimensions 
print(roles_TA)
print(roles_TA.shape)

[['Sierra' 'Sikorski' 'Teaching Assistant']]
(1, 3)


## 2.3 Adding to an array 

- A. Use np.append (google the documentation) to  add the following column with the netid of the TA to the roles_TA array as the last column 
- B. Store as role_TA_net
- C. Print the dimensions of the array

In [3]:
## column to add 
netids = np.array([['s1892']])

In [8]:
## your code here

# add the netid
role_TA_net = np.append(roles_TA, netids, axis=1)

In [12]:
## your code here

# print dimention
print(role_TA_net.shape)

(1, 4)


### 2.4 Numpy Mathemathics. 

The 2-d array below gives you data with the number of goals scored by a country in six editions of the Fifa Soccer World Cup.

Here is the data as a nested list

In [31]:
import numpy as np
# rows and columns
rows = ["Argentina", "Brazil", "Germany", "Spain", "France", "Japan", "Uruguay"]
cols = ["1990", "1994", "1998", "2002", "2006", "2010"]

# matrix of goals
goals= [[8,10, 2, 11, 10, 10], 
         [11, 14, 18, 10, 9, 15], 
         [9, 8, 14 , 14, 16, 29],
         [10, 8, 10, 9, 8, 4],  
         [0, 15, 0, 9, 1, 12],
         [0, 1, 5, 2, 4, 2],
         [0, 0, 4, 0, 11, 4]]       


Using only numpy functions (don't try to convert to a panda dataframe), give me the following: 

- A) How many goals each country scored summing across all the world cup editions?
- B) How many goals were scored in each edition summing across all the countries?
- C) How many goals Brazil scored in 1994?
- D) Which countries scored more than 5 goals in 2010?
- E) Which country scored more goals across all the WC editions?
- F) Which world cup edition had more goals in total?

In [26]:
## your code here


In [99]:
# A) How many goals each country scored summing across all the world cup editions?

# Sum goals across all world cup editions for each country
# axis = 1: row-wise operation
total_goals_country = np.sum(goals, axis = 1)
total_goals_country

array([51, 77, 90, 49, 37, 14, 19])

In [52]:
# B) How many goals were scored in each edition summing across all the countries?

# Sum goals across all countries for each edition
# axis = 0: column-wise operation
total_goals_edition = np.sum(goals, axis=0)
total_goals_edition


array([38, 56, 53, 55, 59, 76])

In [71]:
# C) How many goals Brazil scored in 1994?

# first []: look for Brazil's index in rows
# second []: look for 1994's index in cols
goals[rows.index('Brazil')][cols.index('1994')]

14

In [91]:
# D) Which countries scored more than 5 goals in 2010?

# Countries that scored more than 5 goals in 2010

# convert goals and rows into array
goals = np.array(goals)
rows = np.array(rows)

# pull out 2010's goals
goals_2010 = goals[:, 5]
# filter goals larger than 5
goals_2010 = goals_2010> 5

# filter countries have goals larger than 5
rows [goals_2010]

array(['Argentina', 'Brazil', 'Germany', 'France'], dtype='<U9')

In [108]:
# E) Which country scored the most goals across all the WC editions?

# country scored the most goals
# argmax: return the index of the max number
# look for the country has max goals
rows[np.argmax(total_goals_country)]


'Germany'

In [109]:
# F) Which World Cup edition had the most goals in total?

# edition has the most goals
# argmax: return the index of the max number
# look for the year has max goals
cols[np.argmax(total_goals_edition)]


'2010'

# 3. Practice with iteration/list comprehension (10pts)

Here, we provide you with a list containing the course codes for different McCourt/Georgetown

In [110]:
## course code list 
course_codes = ["PPOL 506", "PPOL 560", "PPOL 564", "SOCI 393"]

## 3.1 Using list comprehension to keep all elements / transform them 

- A. Create a new list---course_codes_ns-- that removes the spaces in each course code--- eg PPOL 506 should become PPOL506
- B. Print `course_codes_ns`

In [119]:
## your code here

# apply replace method for every item in course_codes
course_codes_ns = [x.replace(" ", "") for x in course_codes]

# print
print(course_codes_ns)

['PPOL506', 'PPOL560', 'PPOL564', 'SOCI393']


## 3.2 Using list comprehension to subset a list

- A. using course_codes_ns, create a new list just with courses with ppol in the name; store it as `course_codes_ppol`

In [117]:
## your code here

# keep items in course_codes_ns if item include "PPOL"
course_codes_ppol = [x for x in course_codes_ns if "PPOL" in x]
course_codes_ppol

['PPOL506', 'PPOL560', 'PPOL564']

## 3.3 Dictionary Comprehension 

- A. Create a second list with the grades you which to have in each of these courses
- B. Use a dictionary Comprehension to create a dictionary with keys for the course number, and values for your grade

In [122]:
## your code here

# create list of grades
course_grade = ['A', 'B', 'C']

# create dictionary with items(x) in course_codes_ppol and items(y) in course_grade
# zip: aggregate items from lists
course_grade_dict = {x: y for x, y in zip(course_codes_ppol, course_grade)}

course_grade_dict

{'PPOL506': 'A', 'PPOL560': 'B', 'PPOL564': 'C'}

## 4 - Generators (20pts)

In class, I argued that generators are extremely memory-efficient tool to build repeated tasks in Python. This happens because a generator is a special kind of function that leverages lazy evaluation, and do not store their contents in memory as you would expect a typical iterable to do. Instead, it only computes the element on demand. 

Being suspicious of non-evidence based claim as a data scientist needs to be, you decided to write code to verify this assumption. 

So prove to me with your code that iterating over `range(N)` is indeed more efficient in memory aspects than iterating over a `list(N)` object of the same size. 

<div class="alert alert-block alert-info"> 
    
**Tip:** you can use the function `sys.getsizeof()` from the module `sys` to calcule the size of a object in Python

</div>

In [148]:
## add your response here

# import library
import sys

# Create a generator and a list of the same size
rag = range(100)
lst = list(range(100))

# calculate and print memory
print(sys.getsizeof(rag))
print(sys.getsizeof(lst))

48
856


# 5 - Writing Functions and Numpy (20 pts)


In this exercise, you need to write a functions that returns the `n` closest points to a list of two dimensional points. 

Your function should be named appropriately, and should have two inputs: 

- an two-dimensional array with points and 
- a parameter to give you the number of closest points needed to be printed. 

You should solve this exercise using only numpy functions

To calculate the distance between two points, you can use the euclidean distance as expressed below:


$$d = \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$$

Finally, show that the functions works using the `data_points.csv` available in this same directory. 

In [77]:
## add your response here

def closest_points(data, target, n):
    """
    Find the top n closest points to the target point from a list of two dimensional points.
    
    Imputs:
    data(list): A list of points.
    taget (list): The list of a target point.
    n (int): Indicating how many top closest points the function is looking for. 

    Returns:
    list: A list of top n closest points.

    Example:
    data = [[1, 2], [1, 2]]
    target = [1, 1]
    point = closest_points(data, target, 5)
    print(point)
    """
    # Convert input data into arrays
    points = np.array(data)
    target_point = np.array(target)

    # np.linalg.norm: calculate distance
    # axis = 1: row-wise operation
    distances = np.linalg.norm(points - target, axis=1)

    # argsort: return index after sorting (ascending)
    # [:n] slice the first n rows
    index = np.argsort(distances)[:n]

    # poll out n closest points
    closest_points = points[index]

    return closest_points

In [78]:
import pandas as pd
df = pd.read_csv("data_points.csv")

# apply function
closest_points(df, [4, 5], 5)

array([[ 1, 19],
       [ 3, 22],
       [ 1, 22],
       [24,  5],
       [24,  4]])

# 6 - Creating Pandas Dataframes (10 points)

Now, similar to the problem above, assume you have a spreadsheet with the following information: 

 Students | Grades_PPOL101 | Grades_PPOL202 |
|----------|----------------|----------------|
| Alice    | 85            | 82            |
| Bob      | 90            | 87            |
| Charlie  | 78            | 80            |
| David    | 92            | 94            |
| Eve      | 88            | 89            |

Show me how to create this spreadsheet using: 

- A row-wise approach 
- A column-wise approach


In [45]:
## add your response here

# install pandas
import pandas as pd

In [47]:
# row-Wise approach

# each element is a row
data_r = [
    ['Alice', 85, 82],
    ['Bob', 90, 87],
    ['Charlie', 78, 80],
    ['David', 92, 94],
    ['Eve', 88, 89]  
]

col = ['Students', 'Grades_PPOL101', 'Grades_PPOL202']

data_r = pd.DataFrame(data_r, columns = col)

data_r

Students  Grades_PPOL101  Grades_PPOL202
0    Alice              85              82
1      Bob              90              87
2  Charlie              78              80
3    David              92              94
4      Eve              88              89

In [48]:
# column-wise data 
# each key represents a column
data_c = {
    'Students': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Grades_PPOL101': [85, 90, 78, 92, 88],
    'Grades_PPOL202': [82, 87, 80, 94, 89]
}

# Create the DataFrame
data_c = pd.DataFrame(data_c)
data_c

Students  Grades_PPOL101  Grades_PPOL202
0    Alice              85              82
1      Bob              90              87
2  Charlie              78              80
3    David              92              94
4      Eve              88              89